Repository openshift/baremetal-operator, pull requests merged in 2019-07, with the labels that each got.

#15 pull upstream 20190702
  Makefile
  cmd/make-bm-worker/main.go
  cmd/make-bm-worker/templates/templates.go
  cmd/make-bm-worker/templates/templates_test.go
  cmd/make-virt-host/main.go
  deploy/crds/demo-hosts.yaml
  deploy/crds/metal3_v1alpha1_baremetalhost_crd.yaml
  docs/BaremetalHost_ProvisioningState.dot
  docs/api.md
  docs/dev-setup.md
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
  pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, lgtm, size/L

#16 pull upstream 20190703
  Makefile
  build/Dockerfile
  cmd/manager/main.go
  pkg/version/version.go
Labels: approved, lgtm, size/M

#17 Dockerfile: Sync build change from upstream Dockerfile.
  Dockerfile
Labels: approved, lgtm, size/XS

#19 Add fujitsu iRMC support
  docs/api.md
  pkg/bmc/access.go
  pkg/bmc/access_test.go
  pkg/bmc/irmc.go
Labels: approved, lgtm, size/L

#20 Documentation updates
  README.md
  docs/api.md
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, size/M

#21 Add explicit externally provisioned flag
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
  docs/api.md
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, lgtm, size/L

#23 Configure metrics endpoint.
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#22 Persist firmware and bios data during introspection.
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/M

#24 docs: Document the current set of hw profiles.
  docs/api.md
Labels: approved, lgtm, size/S

#25 pull some firmware inspection fixes from upstream
  pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/M

#27 Reference the current ironic images
  deploy/operator_ironic.yaml
Labels: approved, lgtm, size/S

#26 pull upstream changes to adopt externally provisioned hosts
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/M

#29 Avoid port conflict for metrics endpoint
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#30 pull upstream OpenAPI validation improvements
  .travis.yml
  Gopkg.lock
  Makefile
  deploy/crds/metal3_v1alpha1_baremetalhost_crd.yaml
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/L

#31 convert existing type tests to use subtests
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
Labels: approved, lgtm, size/L

#32 Update to latest gophercloud revision
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/gophercloud/gophercloud/acceptance/openstack/compute/v2/compute.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/testing/fixtures.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/testing/fixtures.go
Labels: approved, lgtm, size/L

#33 only skip inspection for fully provisioned hosts
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/M
