Repository openshift/baremetal-operator, pull requests merged in 2020-06, with the labels that each got.

#75 Bug 1843950: remove infinite reconcile loop when fetching status annotation
  cmd/get-hardware-details/main.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#74 [release-4.5] Bug 1844205: remove infinite reconcile loop when fetching status annotation
  cmd/get-hardware-details/main.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#77 Merge upstream 2020-06-17
  Makefile
  build/Dockerfile
  docs/deploying.md
  go.mod
  hack/Dockerfile.golint
  hack/Dockerfile.operator-sdk
  pkg/provisioner/ironic/ironic.go
  vendor/modules.txt
Labels: approved, lgtm

#70 [release-4.4] Bug 1843230: Read BMH status from annotation
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test
