Repository openshift/baremetal-operator, pull requests merged in 2020-09, with the labels that each got.

#96 Bug 1875558: Always delete found host from Ironic on deletion
  pkg/provisioner/ironic/ironic.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#98 Bug 1879284: Handle StateAvailable when we see it
  pkg/controller/baremetalhost/host_state_machine.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#104 Bug 1879034: Ensure the boot mode is set in ironic before starting inspection
  pkg/controller/baremetalhost/host_state_machine.go
  pkg/controller/baremetalhost/host_state_machine_test.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
