Repository openshift/baremetal-operator, pull requests merged in 2020-04, with the labels that each got.

#60 Vendor build
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: approved, lgtm

#61 Add honza and stbenjam to owners
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#62 Bug 1826418: Add openstack profile to BMO
  docs/api.md
  pkg/hardware/profile.go
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm, ok-to-test

#65 Add bugzilla component information to OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm
