Repository openshift/baremetal-operator, pull requests merged in 2021-04, with the labels that each got.

#139 Merge upstream 2021-03-30
  Makefile
  OWNERS
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/certmanager/certificate.yaml
  config/crd/patches/cainjection_in_baremetalhosts.yaml
  config/crd/patches/webhook_in_baremetalhosts.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/manager.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  docs/api.md
  go.mod
  go.sum
  hack/install-controller-gen.sh
  hack/install-golangci-lint.sh
  hack/unit.sh
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/ironic/ironic.yaml
  main.go
  pkg/bmc/access_test.go
  pkg/bmc/redfish.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/findhost_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/provisioncapacity_test.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  tools/deploy.sh
  tools/install_kustomize.sh
  tools/remove_local_ironic.sh
  tools/run_local_ironic.sh
  vendor/modules.txt
Labels: approved, lgtm

#144 Bug 1949898: modify power_interface for irmc
  pkg/bmc/irmc.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#145 Bug 1951671: Lazily update Node image options in Ironic
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/update_opts.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
