Repository openshift/baremetal-operator, pull requests merged in 2021-06, with the labels that each got.

#151 Bug 1969903: Increase the default $BMO_CONCURRENCY for scale
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  docs/configuration.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#152 Bug 1969487: Disable raid feature for iRMC server
  pkg/bmc/irmc.go
  pkg/provisioner/ironic/prepare_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#153 Bug 1969487: Disable RAID for all drivers
  pkg/bmc/idrac.go
  pkg/bmc/ilo5.go
  pkg/provisioner/ironic/prepare_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#157 Bug 1972374: Don't deprovision provisioned host due to error
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#158 [release-4.8] Bug 1972426: Don't deprovision provisioned host due to error
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#159 [release-4.7] Bug 1972430: Don't deprovision provisioned host due to error
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#161 Merge upstream 2021-06-25
  controllers/metal3.io/baremetalhost_controller.go
  docs/api.md
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm
