Repository openshift/baremetal-operator, pull requests merged in 2021-05, with the labels that each got.

#146 Bug 1956607: Fix resources added to 0000_30_baremetal-operator_01_baremetalhost.crd.yaml
  Dockerfile.ocp
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#147 Bug 1960554: config: use rbacv1 instead of rbacv1beta1
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/render/capm3.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#149 Bug 1965182: IRMC fix missing IPMI credentials in node driver_info
  pkg/bmc/access_test.go
  pkg/bmc/irmc.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
