Repository openshift/baremetal-operator, pull requests merged in 2021-03, with the labels that each got.

#128 Bug 1927678: Backporting BMO extensions to support different reboot modes
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/provisioner.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#127 Bug 1932452: Backport ensure adoption is retried upon failure
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_types_test.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/action_result.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  main.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/result.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#134 Generate BMH CRD with annotations needed for OpenShift
  config/crd/ocp/ocp_kustomization.yaml
Labels: approved, lgtm

#132 Bug 1936407: Backport of BMO code to 4.7 to support different reboot modes
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/provisioner.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#131 Bug 1910352: Fail registration when boot MAC address conflicts
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#135 Copy generated BMH CRD to /manifests directory for CVO to install it
  Dockerfile.ocp
Labels: approved, lgtm

#138 Bug 1941636 - BM worker nodes deployment with virtual media failed while trying to clean raid
  pkg/bmc/access_test.go
  pkg/bmc/ibmc.go
  pkg/bmc/idrac.go
  pkg/bmc/ilo4.go
  pkg/bmc/ipmi.go
  pkg/bmc/redfish.go
  pkg/bmc/redfish_virtualmedia.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testbmc/testbmc.go
Labels: approved, lgtm
