Repository openshift/baremetal-operator, pull requests merged in 2022-01, with the labels that each got.

#198 Bug 2035882: Publish events for all invalid HostFirmwareSettings
  controllers/metal3.io/hostfirmwaresettings_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#199 Bug 2036006: Use integer value in clean steps for HostFirmwareSettings Integer type
  controllers/metal3.io/hostfirmwaresettings_controller.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#200 Bug 2041765: irmc: change BootInterface to ipxe
  pkg/hardwareutils/bmc/access_test.go
  pkg/hardwareutils/bmc/irmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/irmc.go
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-high

#202 Bug 2044496: Update vendor
  apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/irmc.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
