Repository openshift/baremetal-operator, pull requests merged in 2023-04, with the labels that each got.

#261 OCPBUGS-11213: backport: Delay delete of detached hosts
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/metrics.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#262 [4.11] OCPBUGS-11612: allow namespace to continue with terminating when deprovisioning at t…
  controllers/metal3.io/baremetalhost_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#264 OCPBUGS-11036: Merge upstream
  cmd/make-bm-worker/templates/templates.go
  cmd/make-virt-host/main.go
  go.mod
  go.sum
  ironic-deployment/base/ironic.yaml
  ironic-deployment/components/basic-auth/auth.yaml
  ironic-deployment/components/basic-auth/kustomization.yaml
  ironic-deployment/components/keepalived/keepalived_patch.yaml
  ironic-deployment/components/mariadb/mariadb_patch.yaml
  ironic-deployment/overlays/basic-auth_tls/basic-auth_tls.yaml
  pkg/provisioner/ironic/ironic.go
  resources/keepalived-docker/Dockerfile
  resources/keepalived-docker/configure-nonroot.sh
  resources/keepalived-docker/manage-keepalived.sh
  vendor/github.com/google/safetext/LICENSE
  vendor/github.com/google/safetext/common/BUILD.bazel
  vendor/github.com/google/safetext/common/common.go
  vendor/github.com/google/safetext/yamltemplate/BUILD.bazel
  vendor/github.com/google/safetext/yamltemplate/yamltemplate.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#266 OCPBUGS-11310: Revert live-iso validation
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_validation.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#270 OCPBUGS-5833: Merge upstream
  .github/workflows/kubesec.yml
  .github/workflows/lint-docs.yaml
  .markdownlinkcheck.json
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  docs/dev-setup.md
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/provisioner.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#265 OCPBUGS-11870: Create nodes with namespace already prepended
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#273 OCPBUGS-12828: [release 4.13] Store htpasswd files in Secrets instead of ConfigMaps
  ironic-deployment/components/basic-auth/auth.yaml
  ironic-deployment/components/basic-auth/kustomization.yaml
  ironic-deployment/overlays/basic-auth_tls/basic-auth_tls.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
