Repository openshift/baremetal-operator, pull requests merged in 2023-08, with the labels that each got.

#296 OCPBUGS-17363: Trigger reconcile on Secret change
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/preprovisioningimage_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#285 Stop linting when building the image
  Dockerfile.ocp
  Makefile
Labels: approved, lgtm

#294 [release-4.13] OCPBUGS-17229: Set minimum TLS version for webhook to 1.2
  main.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#295 [release-4.13] OCPBUGS-17365: Trigger reconcile on Secret change
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/preprovisioningimage_controller.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
