Repository openshift/baremetal-operator, pull requests merged in 2023-05, with the labels that each got.

#276 OCPBUGS-13080, OCPBUGS-13124: Merge upstream
  .gitignore
  Dockerfile
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  docs/releasing.md
  main.go
  pkg/provisioner/ironic/devicehints/devicehints.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_validation.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#277 [release-4.13] OCPBUGS-13082: Allow by-path devices in root device hints
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  pkg/provisioner/ironic/devicehints/devicehints.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#275 OCPBUGS-12363: release-4.13: Use same settings for provisioner and controller logs
  main.go
  pkg/provisioner/ironic/factory.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#280 OCPBUGS-7581: Merge upstream
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#278 [release-4.12] OCPBUGS-13530: Support /dev/disk/by-path root device hints
  pkg/provisioner/ironic/devicehints/devicehints.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#281 OCPBUGS-13927: Deleting unmanaged BMH get stuck fix
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
