Repository openshift/baremetal-operator, pull requests merged in 2023-11, with the labels that each got.

#316 OCPBUGS-21777: Do not update instance_info and deploy_interface for active nodes
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#321 OCPBUGS-23504: hack for deploying V6-only clusters from dualstack hubs
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/factory_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#319 METAL-376: Re-enable RAID interfaces
  apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac.go
  apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac_virtualmedia.go
  apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/ilo5.go
  apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go
  pkg/hardwareutils/bmc/idrac.go
  pkg/hardwareutils/bmc/idrac_virtualmedia.go
  pkg/hardwareutils/bmc/ilo5.go
  pkg/hardwareutils/bmc/redfish.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac_virtualmedia.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/ilo5.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
