Repository openshift/baremetal-operator, pull requests merged in 2024-03, with the labels that each got.

#324 [release-4.14] OCPBUGS-24409: Don't munge timestamp in structured logs, again
  main.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#337 [release-4.13] OCPBUGS-30629: Do not update instance_info and deploy_interface for active nodes
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#339 NO-ISSUE: Update OWNERS
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#318 OCPBUGS-23324: Backport node poweroff fixes
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
