Repository openshift/baremetal-operator, pull requests merged in 2024-07, with the labels that each got.

#362 OCPBUGS-35559: Bmo sync jul5
  Dockerfile
  Makefile
  README.md
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/hostfirmwarecomponents_controller.go
  controllers/metal3.io/hostfirmwarecomponents_test.go
  go.mod
  go.sum
  hack/e2e/ensure_go.sh
  hack/generate.sh
  hack/golint.sh
  hack/gomod.sh
  hack/manifestlint.sh
  hack/markdownlint.sh
  hack/shellcheck.sh
  hack/unit.sh
  main.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/updateopts.go
  pkg/provisioner/ironic/clients/updateopts_test.go
  pkg/provisioner/ironic/inspecthardware.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/updateopts_test.go
  test/e2e/bmc.go
  test/e2e/e2e_suite_test.go
  test/go.mod
  test/go.sum
  tools/deploy.sh
  tools/run_local_ironic.sh
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#364 NO-ISSUE: Bmo sync jul9
  clean_bmcs.sh
  controllers/metal3.io/baremetalhost_controller.go
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  hack/create_bmcs.sh
  test/createVM/main.go
  test/createVM/templates/VM.xml.tpl
  test/createVM/templates/pool.xml.tpl
  test/createVM/templates/volume.xml.tpl
  test/go.mod
  test/go.sum
  tools/bmh_test/clean_local_bmh_test_setup.sh
Labels: approved, lgtm, jira/valid-reference

#363 OCPBUGS-36673: [4.16] Firmware Update causes BMH to get stuck in Preparing
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/hostfirmwarecomponents_controller.go
  controllers/metal3.io/hostfirmwarecomponents_test.go
  main.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#366 OCPBUGS-37262: fix(redfish): set correct idrac-redfish management interface
  apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go
  pkg/hardwareutils/bmc/redfish.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#367 OCPBUGS-36425: Sync jul 30
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/hostfirmwarecomponents_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
