Repository openshift/baremetal-operator, pull requests merged in 2025-07, with the labels that each got.

#424 OCPBUGS-57472: merge from upstream
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_types_test.go
  config/default/ironic.env
  config/overlays/e2e/ironic.env
  config/render/capm3.yaml
  internal/webhooks/metal3.io/v1alpha1/baremetalhost_validation.go
  internal/webhooks/metal3.io/v1alpha1/baremetalhost_validation_test.go
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/factory_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision.go
  pkg/provisioner/ironic/provision_test.go
  test/vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#420 [4.19] OCPBUGS-56765: Make firmware update handle only a subset of `Spec.Updates`
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#423 OCPBUGS-59133: Unblock BMH direct deletion when detached annotation is present
  controllers/metal3.io/dataimage_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
